name: Build Flutter APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '21'
        
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        
    - name: Create .env file
      run: echo "R0VNSU5JX0FQSV9LRVk9QVEuQWI4Uk42SjFEQzEwYWdybkxWX2dlWWlMQmxVQjBETXNTRFplVy0wbFRvY2FscDlkc0E=" | base64 --decode > .env
      working-directory: flutter_ui
        
    - name: Install dependencies
      run: flutter pub get
      working-directory: flutter_ui
      
    - name: Build APK
      run: flutter build apk --release
      working-directory: flutter_ui
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: instaclear-app-release
        path: flutter_ui/build/app/outputs/flutter-apk/app-release.apk
